#PostgreSQL
development:
  adapter: postgresql
  username: vadmin
  password: p@ssw0rd
  database: messages_dev

test:
  adapter: postgresql
  username: vadmin
  password: p@ssw0rd
  database: messages_test

production:
  adapter: postgresql
  username: postgres
  password: p@ssw0rd
  database: messages
